In [1]:
import numpy as np

In [3]:
# task51
# 创建表示位置(x, y)和颜色(r, g, b, a)的结构化数组
# a = np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
# print(a)

In [4]:
# task52
# 思考形状为(100, 2)的随机向量，求出点与点之间的距离
Z = np.random.random((100,2))
x,y = np.atleast_2d(Z[:,0],Z[:,1])
print(x)
print('-'*30)
print(x.shape)
print('-'*30)
a = (x-x.T)**2
print(a)
print('-'*30)
print(a.shape)
b = (y-y.T)**2
c = np.sqrt(a + b)
print('-'*30)
print(c)
print('-'*30)
# 第二种做法：使用scipy 库可更快
import scipy.spatial as sp
c = sp.distance.cdist(Z,Z)
print(c)

[[0.30536018 0.96777641 0.66491397 0.70055285 0.7466093  0.94331076
  0.82705688 0.16076631 0.38024017 0.32242444 0.75629141 0.90564309
  0.74925419 0.84670814 0.25356762 0.49650818 0.16176082 0.35144426
  0.22005847 0.32107477 0.34794727 0.92288731 0.05552426 0.71578416
  0.53575002 0.43258904 0.54333373 0.12509466 0.06935346 0.86126352
  0.10403398 0.30417376 0.83959078 0.54936896 0.559399   0.53864333
  0.8692228  0.74213875 0.67899805 0.74534573 0.52447875 0.0308612
  0.33905419 0.44955419 0.09758011 0.36382286 0.0970967  0.81051446
  0.89333981 0.06418903 0.31954994 0.27752613 0.4555439  0.85161817
  0.35969479 0.34072544 0.72601905 0.06551524 0.76829368 0.92269481
  0.95291569 0.47606498 0.88252077 0.48183379 0.80587043 0.41209014
  0.2103006  0.9519949  0.48187799 0.45494892 0.94533803 0.89973485
  0.09958048 0.09162464 0.8257433  0.69491699 0.45621726 0.05854772
  0.9929991  0.20830338 0.0019422  0.85521393 0.7884808  0.05760464
  0.14248216 0.80133963 0.47796314 0.3741205  0.7

In [5]:
# task53
# 如何将类型为float(32位)的数组类型转换位integer(32位)
Z = np.arange(10,dtype=np.int32)
print(Z)
print('-'*30)
Z = Z.astype(np.float32,copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]
------------------------------
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [6]:
# task54
# 如何读取下面的文件?
Z = np.genfromtxt('/Users/apple/Desktop/example.txt',delimiter=',')
print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


In [7]:
# task55
# 同numpy数组枚举(enumerate)的等价操作
# 提示: np.ndenumerate, np.ndindex
Z = np.arange(9).reshape(3,3)
print(Z)
print('-'*30)
for i,v in np.ndenumerate(Z):
    print(i,v)
print('-'*30)
for i in np.ndindex(Z.shape):
    print(i,Z[i])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------------------------
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
------------------------------
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [8]:
# task56
# 构造一个二维高斯矩阵
X,Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d = np.sqrt(X**2 + Y**2)
sigma,mu = 1,0
g = np.exp(-((d-mu)**2/(2*sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [9]:
# task57
# 如何在二维数组的随机位置放置p个元素
# 提示: np.put, np.random.choice
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1)
print(Z)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
# task58
# 减去矩阵每一行的平均值
# 提示：mean(axis=,keepdims=)
X = np.random.rand(5,10)
print(X)
print('-'*30)
Y = X - X.mean(axis=1,keepdims= True)
print(Y)

[[0.19657911 0.97166868 0.55547272 0.819874   0.50506534 0.18826932
  0.25804318 0.83644221 0.32162906 0.77953057]
 [0.83356145 0.8595238  0.9886118  0.50786935 0.9397929  0.67674278
  0.34360287 0.74789204 0.09894695 0.73681463]
 [0.19115409 0.508612   0.5233836  0.53979852 0.76836172 0.2377707
  0.97783443 0.11406583 0.95002964 0.20698136]
 [0.23388233 0.28702903 0.01084108 0.54147195 0.51706856 0.57494304
  0.95287165 0.3785574  0.0901186  0.14483203]
 [0.87509427 0.32809306 0.87638565 0.84794056 0.30513505 0.51510803
  0.50891481 0.05133951 0.39982063 0.96136392]]
------------------------------
[[-0.34667831  0.42841126  0.0122153   0.27661659 -0.03819208 -0.3549881
  -0.28521424  0.29318479 -0.22162836  0.23627315]
 [ 0.16022559  0.18618794  0.31527595 -0.1654665   0.26645704  0.00340692
  -0.32973299  0.07455619 -0.5743889   0.06347877]
 [-0.3106451   0.00681281  0.02158441  0.03799933  0.26656253 -0.26402849
   0.47603524 -0.38773336  0.44823045 -0.29481782]
 [-0.13927924 -0.086

In [11]:
# task59
# 如何对数组通过第n列进行排序
# np.argsort(x) 返回的是，从小到大排列的索引值：
# eg：x = np.array([3,1,2]),那么 np.argsort(x)，结果为[1,2,0]，因为 3最大，索引值为0，1最小，索引值为1；
# 所以最小的排在最前，索引值为 1，最大的排在最后，索引值为 0，总结下来为[1,2,0]
a = np.random.randint(0,10,(3,3))
print(a)
print('-'*30)
print(a[a[:,1].argsort()])

[[1 2 6]
 [4 3 2]
 [0 6 5]]
------------------------------
[[1 2 6]
 [4 3 2]
 [0 6 5]]


In [12]:
# task60
# 如何判断一个给定的二维数组存在空列
# 提示：any,~
a = np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

False


In [13]:
# task61
# 从数组中找出与给定值最接近的值
# 提示: np.abs, argmin, flat
a = np.random.uniform(0,1,10)
print(a)
print('-'*30)
b = 1
print(np.abs(a-b).argmin())
print('-'*30)
m = a[np.abs(a-b).argmin()]
print(m)

[0.62855516 0.19712291 0.79174692 0.81545558 0.05358346 0.25024129
 0.42103485 0.46387054 0.02306247 0.0995268 ]
------------------------------
3
------------------------------
0.8154555797693607


In [14]:
# task62
# 思考形状为(1, 3)和(3, 1)的两个数组形状，如何使用迭代器计算它们的和
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
i = np.nditer([A,B,None])
for x,y,z in i:
    z[...] = x + y
print(i.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [15]:
# task63
# 创建一个具有name属性的数组类
# 提示: class method
class NameArray(np.ndarray):
    def __new__(cls,array,name='no name'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self,obj):
        if obj is None:return
        self.info = getattr(obj,'name','no name')
Z = NameArray(np.arange(10),'range_10')
print(Z.name)

range_10


In [16]:
# task64
# 给定一个向量，如何让在第二个向量索引的每个元素加1(注意重复索引)
a = np.ones(10)
i = np.random.randint(0,len(a),20)
np.add.at(a,i,1)
print(a)

[2. 2. 3. 3. 4. 3. 5. 3. 2. 3.]


In [17]:
# task65
# 如何根据索引列表I将向量X的元素累加到数组F
X = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
f = np.bincount(i,X)
print(f)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [18]:
# task66
# 思考(dtype = ubyte)的(w, h, 3)图像，计算唯一颜色的值
w,h = 16,16
i = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = i[...,0]*256*256 + i[...,1]*256 + i[...,2]
n = len(np.unique(F))
print(np.unique(i))

[0 1]


In [19]:
# task67
# 思考如何求一个四维数组最后两个轴的数据和
A = np.random.randint(0,10,(3,4,3,4))
# 第一种做法,这种比较常见，就是用 numpy的实例方法 sum,传入 -1，-2轴：
zj = A.sum(axis=(-2,-1))
print(zj)
print('-'*30)
# 第二种做法
# 将最后两个维度压缩为一个
zj2 = A.reshape(A.shape[:2]+(-1,)).sum(axis=-1)
print(zj2)

[[49 62 51 60]
 [66 52 66 48]
 [48 80 52 55]]
------------------------------
[[49 62 51 60]
 [66 52 66 48]
 [48 80 52 55]]


In [20]:
# task68
# 考虑一维向量D，如何使用相同大小的向量S来计算D的子集的均值，其描述子集索引
# 这比较好解决的方式是，引用 pandas来做：
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
import pandas as pd
a = pd.Series(D).groupby(S).mean()
print(a)

0    0.432505
1    0.638345
2    0.650252
3    0.514762
4    0.426185
5    0.463595
6    0.570453
7    0.616723
8    0.438007
9    0.629639
dtype: float64


In [21]:
# task69
# 如何获得点积的对角线
# 比较基础的解决方式
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
a = np.diag(np.dot(A,B))
print(a)
# 第二种方式，快一点
a = np.sum(A * B.T,axis=1)
# 第三种方式，更快一些
# a = np.einsum('ij,ji->i',A,B)

[2.54561117 1.52826339 1.08633465 0.54525048 1.26910175]


In [22]:
# task70
# 考虑向量[1,2,3,4,5]，如何建立一个新的向量，在每个值之间交错有3个连续的零
a = np.array([1,2,3,4,5])
nz = 3
a0 = np.zeros(len(a)+(len(a)-1)* nz)
a0[::nz+1] = a
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [23]:
# task71
# 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘
# 提示: array[:, :, None]
A = np.ones((5,5,3))
B = 2 * np.ones((5,5))
a = A * B[:,:,None]
print(a)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [24]:
# task72
# 如何对一个数组中任意两行做交换
# 提示: array[[2,3]] = array[[3,2]]
A = np.arange(25).reshape((5,5))
print(A)
print('-'*30)
A[[2,3]] = A[[3,2]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
------------------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [20 21 22 23 24]]


In [25]:
# task73
# 思考描述10个三角形（共享顶点）的一组10个三元组，找到组成所有三角形的唯一线段集
# 提示: repeat, np.roll, np.sort, view, np.unique
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape((len(F)*3,2))
F = np.sort(F,axis=1)
G = F.view(dtype=[('p0',F.dtype),('p1',F.dtype)])
G = np.unique(G)
print(G)

[( 0, 52) ( 0, 68) ( 4, 18) ( 4, 52) ( 6, 42) ( 6, 46) (14, 17) (14, 70)
 (17, 55) (17, 70) (17, 90) (18, 26) (18, 37) (18, 52) (26, 37) (37, 46)
 (37, 67) (38, 56) (38, 93) (42, 46) (46, 67) (51, 54) (51, 81) (52, 68)
 (54, 81) (55, 90) (56, 93) (82, 82) (82, 99)]


In [26]:
# task74
# 给定一个二进制的数组C，如何生成一个数组A满足np.bincount(A)==C
# 提示：np.repeat
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(C)
print('-'*30)
print(A)

[0 2 1 1 2 0 1]
------------------------------
[1 1 2 3 4 4 6]


In [27]:
# task75
# 如何通过滑动窗口计算一个数组的平均数
def moving_average(a,n=3):
    ret = np.cumsum(a,dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:]/n
Z = np.arange(20)
print(moving_average(Z,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [28]:
# task76
# 思考以为数组Z，构建一个二维数组，
# 其第一行是(Z[0],Z[1],Z[2])，
# 然后每一行移动一位，最后一行为 (Z[-3],Z[-2],Z[-1])
from numpy.lib import stride_tricks
def rolling(a,window):
    shape = (a.size - window +1,window)
    strides = (a.itemsize,a.itemsize)
    return stride_tricks.as_strided(a,shape = shape,strides=strides)
Z = rolling(np.arange(10),3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [30]:
# task77
# 如何对布尔值取反，或改变浮点数的符号(sign)
Z = np.random.randint(0,2,100)
print(Z)
print('-'*30)
np.logical_not(Z,out=Z)
print(Z)
print('-'*30)
# 第二种：改变浮点数的符号
Z = np.random.uniform(-1,1,100)
print(Z)
print('-'*30)
np.negative(Z,out=Z)
print(Z)

[0 1 1 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 1 0 1 0 1 1 0 0 0 0 0 1
 0 1 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 1
 1 1 0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 1 0 1]
------------------------------
[1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 0 1 1 1 0 1 0 1 0 0 1 1 1 1 1 0
 1 0 0 0 0 1 0 1 1 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0
 0 0 1 0 1 1 1 1 0 1 0 0 1 1 1 0 1 1 1 0 0 0 0 0 1 0]
------------------------------
[ 0.64697985 -0.18040662  0.27859519  0.52989908  0.18043116 -0.5668052
 -0.37989133  0.09280121 -0.28029615  0.72911482 -0.99383301 -0.30472293
 -0.73666128 -0.71215893 -0.02759495  0.46810469  0.93272098  0.99804833
  0.84282085 -0.79723485  0.92206941 -0.03826974 -0.3159885  -0.896707
  0.24445738 -0.21294333 -0.48489213 -0.72981184  0.1937056   0.34953007
  0.35181521  0.67354046 -0.78997521  0.54589457 -0.60487286  0.22131793
  0.02085795  0.9677462  -0.99464944 -0.59420944  0.05813676 -0.92333828
  0.06747032  0.718695

In [31]:
# task78
# 思考两组点集P0和P1去描述一组线(二维)和一个点p,
# 如何计算点p到每一条线 i (P0[i],P1[i])的距离
def distance(p0,p1,p):
    T = p1 - p0
    L = (T ** 2).sum(axis=1)
    U = -((p0[:,0]-p[...,0])* T[:,0] + (p0[:,1]-p[...,1]*T[:,1])/L)
    U = U.reshape(len(U),1)
    D = p0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
p0 = np.random.uniform(-10,10,(10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2))
print(distance(p0,p1,p))

[625.1160417  163.69590143  53.08004567  52.85425055 683.3881356
 151.80872148 823.28273246 445.60814278 367.74575551 780.81302874]


In [32]:
# task79
# 考虑两组点集P0和P1去描述一组线(二维)和一组点集P，
# 如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离
p0 = np.random.uniform(-10,10,(10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(10,2))
print(np.array([distance(p0,p1,p_i) for p_i in p]))

[[6.37361700e+02 2.55868364e+01 5.09446729e+03 4.82712040e+02
  3.25140480e+03 1.93572029e+03 1.04313213e+03 2.36517711e+03
  1.87723734e+02 1.89799163e+02]
 [6.45202146e+02 1.20757619e+02 1.25578707e+03 7.03638434e+01
  6.18315339e+02 2.01724085e+02 7.20925289e+01 4.77843383e+02
  2.60066123e+03 1.98878791e+03]
 [9.55053543e+02 1.43647893e+02 3.27944959e+02 2.04171151e+02
  1.83449708e+01 7.18222569e+02 1.63258428e+02 1.16506197e+03
  3.27463257e+03 2.51537241e+03]
 [1.50703620e+00 7.27395373e+01 3.18897700e+03 2.08201089e+02
  1.94435197e+03 8.74792337e+02 5.60898516e+02 9.53977410e+02
  1.19642148e+03 8.91646135e+02]
 [9.23981339e+02 4.41161711e+00 5.95241460e+03 6.06362067e+02
  3.83991870e+03 2.41339816e+03 1.26025915e+03 3.00059184e+03
  8.10947429e+02 6.76748443e+02]
 [5.48155241e+02 1.13568767e+02 1.54636517e+03 2.84864083e+01
  8.17639202e+02 4.03599707e+01 1.45398663e+02 2.62630634e+02
  2.38958867e+03 1.82387502e+03]
 [9.36776670e+02 3.49434888e+00 5.99070429e+03 6.11888841e

In [34]:
# task81
# 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],
# 如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]
# 提示：stride_tricks.as_strided
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [35]:
# task82
# 计算矩阵的秩
# 提示: np.linalg.matrix_rank
Z = np.random.uniform(0,1,(10,10))
rank1 = np.linalg.matrix_rank(Z)
print(rank1)

10


In [36]:
# task83
# 如何找出数组中出现频率最高的值
# np.bincount, argmax
Z = np.random.randint(0,10,50)
print(Z)
print('-'*30)
print(np.bincount(Z))
print('-'*30)
print(np.bincount(Z).argmax())

[1 2 2 8 8 2 8 7 1 1 5 8 7 3 5 8 9 6 1 9 6 5 3 7 5 2 8 4 8 7 8 1 5 2 4 4 6
 2 0 9 7 8 6 2 5 2 4 9 3 2]
------------------------------
[1 5 9 3 4 6 4 5 9 4]
------------------------------
2


In [37]:
# task84
# 从一个10x10的矩阵中提取出连续的3x3区块
# 第一种做法
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
c = stride_tricks.as_strided(Z,shape=(i,j,n,n),strides=Z.strides+Z.strides)
print(c)

[[[[2 3 0]
   [4 4 1]
   [0 1 4]]

  [[3 0 4]
   [4 1 0]
   [1 4 3]]

  [[0 4 4]
   [1 0 2]
   [4 3 4]]

  [[4 4 3]
   [0 2 4]
   [3 4 4]]

  [[4 3 2]
   [2 4 3]
   [4 4 4]]

  [[3 2 2]
   [4 3 2]
   [4 4 0]]

  [[2 2 2]
   [3 2 0]
   [4 0 2]]

  [[2 2 1]
   [2 0 0]
   [0 2 4]]]


 [[[4 4 1]
   [0 1 4]
   [1 4 2]]

  [[4 1 0]
   [1 4 3]
   [4 2 0]]

  [[1 0 2]
   [4 3 4]
   [2 0 1]]

  [[0 2 4]
   [3 4 4]
   [0 1 4]]

  [[2 4 3]
   [4 4 4]
   [1 4 4]]

  [[4 3 2]
   [4 4 0]
   [4 4 2]]

  [[3 2 0]
   [4 0 2]
   [4 2 0]]

  [[2 0 0]
   [0 2 4]
   [2 0 2]]]


 [[[0 1 4]
   [1 4 2]
   [3 3 1]]

  [[1 4 3]
   [4 2 0]
   [3 1 4]]

  [[4 3 4]
   [2 0 1]
   [1 4 0]]

  [[3 4 4]
   [0 1 4]
   [4 0 0]]

  [[4 4 4]
   [1 4 4]
   [0 0 2]]

  [[4 4 0]
   [4 4 2]
   [0 2 3]]

  [[4 0 2]
   [4 2 0]
   [2 3 3]]

  [[0 2 4]
   [2 0 2]
   [3 3 2]]]


 [[[1 4 2]
   [3 3 1]
   [0 4 2]]

  [[4 2 0]
   [3 1 4]
   [4 2 4]]

  [[2 0 1]
   [1 4 0]
   [2 4 3]]

  [[0 1 4]
   [4 0 0]
   [4 3 4]]

  [[1 4 4]
   

In [38]:
# task85
# 创建一个满足 Z[i,j] == Z[j,i]的二维数组子类
# 提示: class method
class Symetric(np.ndarray):
    def __setitem__(self, key, value):
        i,j = key
        super(Symetric,self).__setitem__((i,j),value)
        super(Symetric,self).__setitem__((j,i),value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9 17  3  5  9]
 [17  6 12 13  9]
 [ 3 12  1 42 14]
 [ 5 13 42  2 15]
 [ 9  9 14 15  0]]


In [39]:
# task86
# 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)
# 提示: np.tensordot
p,n = 10,20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M,V,axes=[[0,2],[0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [40]:
# task87
# 对于一个16x16的数组，如何得到一个区域的和(区域大小为4x4)
# 提示: np.add.reduceat
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z,np.arange(0,Z.shape[0],k),axis=0),\
                    np.arange(0,Z.shape[1],k),axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [41]:
# task88
# 如何利用numpy数组实现Game of Life?
# 提示: Game of Life , Game of Life有哪些图形
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] + \
         Z[1:-1,0:-2] + Z[1:-1,2:] + Z[2:,0:-2] + Z[2:,1:-1] + Z[2:,2:])
    birth = (N==3) & (Z[1:-1,1:-1] == 0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1])
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100):Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [42]:
# task89
# 如何找到一个数组的第n个最大值?
# 提示: np.argsort | np.argpartition
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
# 第一种方法
print(Z[np.argsort(Z)[-n:]])
print('-'*30)
# 第二种方法
print(Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
------------------------------
[9999 9998 9997 9996 9995]


In [43]:
# task90
# 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)
# 提示: np.indices
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape,dtype=int)
    ix = ix.reshape(len(arrays),-1).T
    for n,arr in enumerate(arrays):
        ix[:,n] = arrays[n][ix[:,n]]
    return ix
print(cartesian(([1,2,3],[4,5],[6,7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [44]:
# task91
# 如何从一个常规数组中创建记录数组(record array)
# 提示: np.core.records.fromarrays
Z = np.array([('Hello',2.5,3),('World',3.6,2)])
R = np.core.records.fromarrays(Z.T,names='col1,col2,col3',formats='S8,f8,i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [45]:
# task92
# 思考一个大向量Z, 用三种不同的方法计算它的立方
# 提示: np.power, *, np.einsum
x = np.random.rand(5)
print(np.power(x,3))
print(x*x*x)
print(np.einsum('i,i,i->i',x,x,x))

[0.05500651 0.49227623 0.53329787 0.25470116 0.94487846]
[0.05500651 0.49227623 0.53329787 0.25470116 0.94487846]
[0.05500651 0.49227623 0.53329787 0.25470116 0.94487846]


In [46]:
# task93
# 考虑两个形状分别为(8,3) 和(2,2)的数组A和B.
# 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)
# 提示: np.where
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[...,np.newaxis,np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 6]


In [47]:
# task94
# 思考一个10x3的矩阵，如何分解出有不全相同值的行 (如 [2,2,3])
Z = np.random.randint(0,5,(10,3))
print(Z)
print('-'*30)
# 第一种方法
# 所有dtype数组的解决方案(包括字符串数组和记录数组)
E = np.all(Z[:,1:] == Z[:,:-1],axis=1)
U = Z[~E]
print(U)
print('-'*30)
# 第二种做法
# 解只适用于数字数组，适用于Z中的任意列数
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 1 4]
 [0 3 4]
 [1 3 0]
 [2 2 3]
 [4 3 2]
 [1 4 2]
 [4 2 3]
 [4 2 2]
 [0 0 4]
 [4 1 0]]
------------------------------
[[0 1 4]
 [0 3 4]
 [1 3 0]
 [2 2 3]
 [4 3 2]
 [1 4 2]
 [4 2 3]
 [4 2 2]
 [0 0 4]
 [4 1 0]]
------------------------------
[[0 1 4]
 [0 3 4]
 [1 3 0]
 [2 2 3]
 [4 3 2]
 [1 4 2]
 [4 2 3]
 [4 2 2]
 [0 0 4]
 [4 1 0]]


In [48]:
# task95
# 将一个整数向量转换为二进制矩阵
# 提示: np.unpackbits
i = np.array([0,1,2,3,15,16,32,64,128])
B = ((i.reshape(-1,1) & (2 ** np.arange(8))) != 0).astype(int)
print(B[:,::-1])
print('-'*30)
# 第二种做法
i = np.array([0,1,2,3,15,16,32,64,128],dtype=np.uint8)
print(np.unpackbits(i[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
------------------------------
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [49]:
# task96
# 给定一个二维数组，如何提取出唯一的行
# 提示: np.ascontiguousarray
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void,Z.dtype.itemsize * Z.shape[1])))
_,idx = np.unique(T,return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]


In [50]:
# task97
# 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数
# 提示: np.einsum
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print(np.einsum('i->',A)) # np.sum(A)
print('-'*30)
print(np.einsum('i,i->i',A,B)) # A * B
print('-'*30)
print(np.einsum('i,i',A,B)) # np.inner(A,B)
print('-'*30)
print(np.einsum('i,j->ij',A,B)) # np.outer(A,B)

4.651178378101923
------------------------------
[0.07977161 0.09980326 0.36803221 0.08572339 0.02147523 0.57154339
 0.3225745  0.02441308 0.09015629 0.79350837]
------------------------------
2.4570013397410166
------------------------------
[[0.07977161 0.04916871 0.09619532 0.02462129 0.00791812 0.08577838
  0.05425739 0.01024845 0.010639   0.10550149]
 [0.16192141 0.09980326 0.19525846 0.0499766  0.01607231 0.17411402
  0.11013232 0.02080243 0.02159518 0.21414824]
 [0.30519698 0.18811382 0.36803221 0.09419822 0.03029383 0.32817819
  0.2075825  0.03920938 0.04070359 0.40363654]
 [0.277739   0.17118959 0.33492107 0.08572339 0.02756835 0.29865264
  0.18890671 0.03568179 0.03704157 0.36732215]
 [0.21635349 0.13335349 0.26089725 0.06677692 0.02147523 0.23264482
  0.1471548  0.02779545 0.02885469 0.28613709]
 [0.53152014 0.3276123  0.64095172 0.16405225 0.05275865 0.57154339
  0.36151826 0.06828566 0.07088792 0.70295896]
 [0.4742633  0.29232098 0.57190661 0.14638008 0.04707534 0.50997513

In [51]:
# task98
# 考虑一个由两个向量描述的路径(X,Y)，
# 如何用等距样例(equidistant samples)对其进行采样(sample)
# 提示: np.cumsum, np.interp
phi = np.arange(0,10*np.pi,0.1)
a = 1
x = a * phi * np.cos(phi)
y = a * phi * np.sin(phi)
dr = (np.diff(x) ** 2 + np.diff(y) ** 2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0,r.max(),200)
x_int = np.interp(r_int,r,x)
y_int = np.interp(r_int,r,y)

In [52]:
# task99
# 给定一个整数n 和一个二维数组X，
# 从X中选择可以被解释为从多n度的多项分布式的行，
# 即这些行只包含整数对n的和
# 提示: np.logical_and.reduce, np.mod
from functools import reduce
X = np.asarray([[1,0,3,8],[2,0,1,1],[1.5,2.5,1,0]])
n = 4
M = np.logical_and.reduce(np.mod(X,1) == 0,axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [53]:
# task100
# 对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值.
# 提示: np.percentile
X = np.random.randn(100)
n = 1000
idx = np.random.randint(0,X.size,(n,X.size))
means = X[idx].mean(axis = 1)
confint = np.percentile(means,[2.5,97.5])
print(confint)

[-0.12676221  0.20885055]
