In [1]:
# numpy_100_puzzles

# task1
# Import the numpy package under the name np
# 以np的名称导入numpy包
import numpy as np

In [2]:
# task2
# Print the numpy version and the configuration
# 打印numpy版本和配置
a = np.__version__
print(a)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']


In [3]:
# task3
# Create a null vector of size 10
# 创建一个大小为10的空向量
ar1 = np.zeros((10))
print(ar1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# task4
# How to find the memory size of any array
# 如何找到任何数组的内存大小
print(ar1.dtype)
a = ar1.size * ar1.itemsize
print(a)
print('该数组共占内存%d bytes' % a)

float64
80
该数组共占内存80 bytes


In [5]:
# task5
# How to get the documentation of the numpy add function
# from the command line
# 如何从命令行获得numpy add函数的文档
a = np.info(np.add)
help(a)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [6]:
# task6
# Create a null vector of size 10 but the fifth value which is 1
# 创建一个大小为10但第五个值为1的空向量
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
# task7
# Create a vector with values ranging from 10 to 49
# 创建一个值从10到49的向量
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# task8
# Reverse a vector (first element becomes last)
# 反转一个向量(第一个元素变成最后一个)
a = np.arange(2,12)
b = a[::-1]
print(b)

[11 10  9  8  7  6  5  4  3  2]


In [9]:
# task9
# Create a 3x3 matrix with values ranging from 0 to 8
# 创建一个3x3的矩阵，其值从0到8
ar1 = np.arange(9).reshape((3,3))
print(ar1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# task10
# Find indices of non-zero elements from [1,2,0,0,4,0]
# 查找[1,2,0,0,4,0]中非零元素的索引
# 第一种做法
a = np.array([1,2,0,0,4,0])
print(a)
print('-'*30)
b = np.where(a != 0)
print(b)
print('-'*30)
# 第二种做法
c = np.nonzero([1,2,0,0,4,0])
print(c)

[1 2 0 0 4 0]
------------------------------
(array([0, 1, 4]),)
------------------------------
(array([0, 1, 4]),)


In [11]:
# task11
# Create a 3x3 identity matrix
# 创建一个3x3单位矩阵
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# task12
# Create a 3x3x3 array with random values
# 创建一个随机值的3x3x3数组
a = np.random.random((3,3,3))
print(a)

[[[0.87407682 0.03846413 0.04727434]
  [0.9027128  0.50076378 0.46149868]
  [0.23599669 0.96877659 0.73863505]]

 [[0.40384065 0.86212269 0.00824019]
  [0.9592884  0.78507362 0.32249149]
  [0.68714393 0.60585957 0.8262829 ]]

 [[0.26789322 0.69893652 0.36957537]
  [0.96449701 0.7040175  0.45812104]
  [0.9215238  0.01160888 0.23903919]]]


In [13]:
# task13
# Create a 10x10 array with random values and find the minimum and maximum values
# 用随机值创建一个10x10的数组，并找出最小值和最大值
a = np.random.random((10,10))
print(a)
b = a.max()
c = a.min()
print('该数组最大值为 %.6f' % b)
print('该数组最小值为 %.6f' % c)

[[0.59648057 0.83929559 0.93734462 0.3846698  0.24655406 0.61440593
  0.40178744 0.83839002 0.74031376 0.60483611]
 [0.28112862 0.76422044 0.93913875 0.99471993 0.86266051 0.20743354
  0.54313174 0.53565732 0.38064101 0.191275  ]
 [0.88262942 0.73447402 0.66941107 0.80751822 0.46304995 0.58898039
  0.47469569 0.75412915 0.34831853 0.4326496 ]
 [0.75134044 0.4158975  0.49203771 0.00208329 0.77162617 0.08574156
  0.05165993 0.47769641 0.65331841 0.67731991]
 [0.87666467 0.40530841 0.42268506 0.64839955 0.64921464 0.41173978
  0.59424166 0.32772366 0.90049632 0.52205073]
 [0.97370102 0.01978921 0.31553404 0.95875925 0.92573178 0.35812698
  0.10682319 0.18328097 0.02389297 0.87549331]
 [0.07196797 0.9520177  0.31123695 0.81393538 0.01698285 0.36570992
  0.13631522 0.26321723 0.13206478 0.12623152]
 [0.06700035 0.30823316 0.22575751 0.30480665 0.39311467 0.10641889
  0.83726866 0.76524631 0.27132642 0.69536393]
 [0.53425209 0.22545141 0.37568155 0.21021787 0.73110223 0.48121632
  0.62582445

In [14]:
# task14
# Create a random vector of size 30 and find the mean value
# 创建一个大小为30的随机向量，并求其平均值
a = np.random.random(30)
print(a)
print('-'*30)
print(a.mean())

[0.07167842 0.17775334 0.42249504 0.56054308 0.31258894 0.71915376
 0.0862239  0.41377002 0.94691212 0.9839008  0.01880613 0.73301745
 0.70032303 0.55913846 0.43584019 0.26843118 0.62649031 0.66096043
 0.28331564 0.90796845 0.55845195 0.11773597 0.47702384 0.26221641
 0.59794401 0.53141391 0.92385076 0.68727426 0.6323139  0.30799112]
------------------------------
0.49951756082576954


In [15]:
# task15
# Create a 2d array with 1 on the border and 0 inside
# 创建一个2d数组，边界为1，内部为0
a = np.ones((5,4))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [17]:
# task16
# How to add a border (filled with 0's) around an existing array?
# 如何添加边界(填满0's)周围的一个现有的数组?
# 第一种做法
a = np.zeros((5,7))
b = np.random.random((3,5))
a[1:-1,1:-1] = b
print(a)

[[0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.09624583 0.20230695 0.09142724 0.57633067 0.78399018
  0.        ]
 [0.         0.74226155 0.48981468 0.15514842 0.26116819 0.31803061
  0.        ]
 [0.         0.55330199 0.07870671 0.06561877 0.97595479 0.17972007
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]]


In [18]:
# 第二种做法
z = np.ones((5,5))
# np.pad 是对数组 进行填充的方法
z = np.pad(z,pad_width = 1,mode='constant',constant_values =0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [19]:
# task17
# What is the result of the following expression?
# 下面这个表达式的结果是什么?
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1
print(0 * np.nan) # 结果为 nan
print(np.nan == np.nan) # 结果为 False
print(np.inf > np.nan) # 结果为 False,且 np.inf 表示+∞，是没有确切的数值的,类型为浮点型
print(np.nan - np.nan) # 结果为 nan
print(np.nan in set([np.nan])) # 结果为 True
print(0.3 == 3 * 0.1) # 结果为 False

nan
False
False
nan
True
False


In [20]:
# task18
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
# 创建一个5x5矩阵，值为1、2、3、4，正好位于对角线下方
a = np.eye(5)
print(a)
print('-'*30)
b = a.cumsum(axis=0)
c = b.cumsum(axis=1)
print(b)
print('-'*30)
print(c)
print('-'*30)
# 第二种做法
z = np.diag(np.arange(1,5))
print(z)
print('-'*30)
z = np.diag(np.arange(1,5),k=-1)
print(z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
------------------------------
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
------------------------------
[[1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 2.]
 [1. 2. 3. 3. 3.]
 [1. 2. 3. 4. 4.]
 [1. 2. 3. 4. 5.]]
------------------------------
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
------------------------------
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [21]:
# task19
# Create a 8x8 matrix and fill it with a checkerboard pattern
# 创建一个8x8的矩阵，并用一个棋盘图案填充它
a = np.zeros((8,8))
print(a)
print('-'*30)
a[1::2,::2] = 1
print(a)
print('-'*30)
a[::2,1::2] = 1
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
------------------------------
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
------------------------------
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [22]:
# task20
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
# 考虑一个(6,7,8)形状数组，第100个元素的下标(x,y,z)是多少
a = np.zeros((6,7,8))
print(a)
print('-'*30)
b = np.unravel_index(99,a.shape)
print(b)

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0

In [23]:
# task21
# Create a checkerboard 8x8 matrix using the tile function
# 使用tile函数创建一个8x8的棋盘矩阵
# 就是 将[[0,1],[1,0]] 向横、纵铺4行、4列
a = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
# task22
# Normalize a 5x5 random matrix
# 标准化一个5x5随机矩阵
# 第一种
a = np.random.random((5,5))
b = a
print(a)
print('-'*30)
a = (a - np.mean(a)) / (np.std(a))
print(a)
print('-'*30)

# 第二种直接引入 sklearn模块中的 scale
from sklearn.preprocessing import scale as sc
b = sc(b)
print(b)
print('-'*30)

[[0.16142339 0.79870583 0.17864338 0.86845434 0.43926668]
 [0.09109995 0.45597371 0.49723758 0.65523112 0.61880311]
 [0.60438981 0.6123302  0.71412538 0.73845528 0.89562626]
 [0.76912882 0.76945683 0.72208434 0.02839955 0.11794216]
 [0.55711154 0.79458281 0.11223238 0.14330672 0.29035617]]
------------------------------
[[-1.24428241  1.06115827 -1.18198716  1.31348135 -0.23915317]
 [-1.49868534 -0.17871361 -0.02943692  0.54212242  0.41034002]
 [ 0.3581983   0.38692355  0.75517901  0.84319514  1.41177881]
 [ 0.95416013  0.95534675  0.78397145 -1.72551105 -1.40158063]
 [ 0.18716384  1.04624279 -1.42223643 -1.30982149 -0.77785362]]
------------------------------
[[-1.04265494  0.83944261 -1.0306381   1.13496417 -0.12340232]
 [-1.30908349 -1.71801784  0.2027546   0.5009315   0.54528894]
 [ 0.63557492 -0.55128868  1.04240525  0.74840377  1.57632879]
 [ 1.25970783  0.62118718  1.07321725 -1.36299156 -1.32018944]
 [ 0.45645567  0.80867674 -1.28773899 -1.02130787 -0.67802597]]
---------------

In [25]:
# task23
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)
# 创建一个自定义dtype，将颜色描述为四个无符号字节(RGBA)
a = np.dtype([('r',np.ubyte),('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])
print(a)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [26]:
# task24
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
# 用一个5x3矩阵乘以一个3x2矩阵(实矩阵乘积)
a = np.arange(15).reshape((5,3))
print(a)
print('-'*30)
b = np.arange(1,13,2).reshape((3,2))
print(b)
print('-'*30)
c = a.dot(b)
print(c)
print('-'*30)
# 第二种做法：Python 3.5及以上版本的替代解决方案
c = np.ones((5,3)) @ np.ones((3,2))
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
------------------------------
[[ 1  3]
 [ 5  7]
 [ 9 11]]
------------------------------
[[ 23  29]
 [ 68  92]
 [113 155]
 [158 218]
 [203 281]]
------------------------------
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [27]:
# task25
# Given a 1D array, negate all elements which are between 3 and 8, in place
# 给定一个1D数组，对所有在3和8之间的元素进行反运算
a = np.random.randint(2,20,10)
print(a)
print('-'*30)
a = np.where((a >= 3)&(a <= 8),-a,a)
print(a)
print('-'*30)
# 第二种做法
z = np.arange(11)
z[(z >= 3) & (z <= 8)] *= -1
print(z)

[16 11  5 14 12 14  9  5  3  9]
------------------------------
[16 11 -5 14 12 14  9 -5 -3  9]
------------------------------
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [28]:
# task26
# What is the output of the following script?
# 以下脚本的输出是什么
print(sum(range(5),-1)) # 显示为 9
print('-'*30)
from numpy import *
print(sum(range(5)))
print('-'*30)
print(sum(range(5),-1)) # 显示为 10，这里应用的sum 其实是 np.sum，即，实际为 numpy.sum(a,axis=None)

9
------------------------------
10
------------------------------
10


In [29]:
# task27
# Consider an integer vector Z, which of these expressions are legal?
# 考虑一个整数向量Z,下列表达合法的是哪个?
z = np.array([10])
print(z) # 结果为 [10]
print(z ** z) # 结果为 [10000000000]
print(2 << z >> 2) # 结果为[512]
print(z < -z) # 结果为 [False]
print(1j*z) # 结果为 [0.+10.j]
print(z/1/1) # 结果为 [10.]
print(z<z>z) # 结果为 [False]

[10]
[10000000000]
[512]
[False]
[0.+10.j]
[10.]
[False]


In [30]:
# task28
# 下列表达式的结果是什么?
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)
# a = np.array(0)/np.array(0) # 出现 warning错误，实际为 nan
# print(a)
# a = np.array(0) // np.array(0)
# print(a) # 结果为0
a = np.array([np.nan]).astype(int).astype(float)
print(a) # 结果为 -9.22337e+18

[-9.22337204e+18]


In [31]:
# task29
# How to round away from zero a float array ?
# 如何从零四舍五入浮点数组
a = np.random.uniform(-10,+10,10)
print(a)
print('-'*30)
b = np.copysign(np.ceil(np.abs(a)),a)
print(b)
print('-'*30)
# 第二种做法：np.ceil即为上限，np.floor 为下限
# 即：大于0时，向上取整；小于0时，向下取整；
c = np.where(a>0,np.ceil(a),np.floor(a))
print(c)

[ 1.55077728  8.30035366 -3.44333251  0.95805042 -1.96429249  3.44006644
 -9.98710121 -6.32190385  9.88920258 -0.79425486]
------------------------------
[  2.   9.  -4.   1.  -2.   4. -10.  -7.  10.  -1.]
------------------------------
[  2.   9.  -4.   1.  -2.   4. -10.  -7.  10.  -1.]


In [32]:
# task30
# 如何找到两个数组之间的共同值?
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
print(a1)
print('-'*30)
print(a2)
print('-'*30)
b = np.intersect1d(a1,a2)
print(b)

[8 9 2 2 2 6 5 8 3 0]
------------------------------
[3 9 6 4 4 0 8 5 3 7]
------------------------------
[0 3 5 6 8 9]


In [33]:
# task31
# How to ignore all numpy warnings (not recommended)?
# 如何忽略所有numpy警告(不推荐)?
with np.errstate(all='ignore'):
    np.arange(3) / 0

In [34]:
# task32
# Is the following expressions true?
# 下列表达正确吗?
# print(np.sqrt(-1) == np.emath.sqrt(-1)) # 结果显示为 False

In [35]:
# task33
# 如何得到昨天，今天和明天的日期?
yesterday1 = np.datetime64('today') - np.timedelta64(1)
today1 = np.datetime64('today')
tomorrow1 = np.datetime64('today') + np.timedelta64(1)
print(yesterday1)
print('-'*30)
print(today1)
print('-'*30)
print(tomorrow1)
print('-'*30)
print(np.datetime64('2009-01-01') - np.datetime64('2008-01-01'))

2022-04-11
------------------------------
2022-04-12
------------------------------
2022-04-13
------------------------------
366 days


In [36]:
# task34
# 如何获得2016年7月对应的所有日期
a = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [37]:
# task35
# 如何计算((A+B)*(A/2))到位(没有副本)?
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[-1.5 -1.5 -1.5]


In [38]:
# task36
# 用5种不同的方法提取随机数组中的整数部分
a = np.random.uniform(0,10,10)
print(a)
print('-'*30)
# 第一种
print(a - a%1)
# 第二种
print(a // 1)
# 第三种
print(np.floor(a))
# 第四种
print(np.ceil(a)-1)
# 第五种
print(a.astype(int))
# 第六种
print(np.trunc(a))

[9.18674803 2.22833039 5.34524139 8.97816491 1.47854541 5.90875315
 0.73976619 9.73350332 3.88273781 9.93420539]
------------------------------
[9. 2. 5. 8. 1. 5. 0. 9. 3. 9.]
[9. 2. 5. 8. 1. 5. 0. 9. 3. 9.]
[9. 2. 5. 8. 1. 5. 0. 9. 3. 9.]
[9. 2. 5. 8. 1. 5. 0. 9. 3. 9.]
[9 2 5 8 1 5 0 9 3 9]
[9. 2. 5. 8. 1. 5. 0. 9. 3. 9.]


In [39]:
# task37
# 创建一个5x5的矩阵且每一行的值范围为从0到4
a = np.zeros((5,5))
a1 = np.arange(5)
a += a1
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [40]:
# task38
# 如何用一个生成10个整数的函数来构建数组
def gen():
    for x in range(10):
        yield x
a = np.fromiter(gen(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [41]:
# task39
# 创建一个大小为10的向量， 值域为0到1，不包括0和1
a = np.linspace(0,1,12,endpoint=True)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [42]:
# task40
# 创建一个大小为10的随机向量并对其排序
a = np.random.random(10)
a.sort()
print(a)

[0.00544639 0.04718408 0.06102418 0.14811162 0.25385507 0.29372748
 0.3072336  0.41281501 0.8146714  0.83902202]


In [43]:
# task41
# 如何求和一个小数组比np.sum更快
a = np.arange(10)
print(np.add.reduce(a))

45


In [45]:
# task42
# 考虑两个随机数组A和B，检查它们是否相等
a = np.random.randint(0,2,5)
print(a)
print('-'*30)
b = np.random.randint(0,2,5)
print(b)
print('-'*30)
# 假设array的形状(shape)相同和一个误差容限（tolerance)
eq = np.allclose(a,b)
print(eq)
# 检查形状和元素值，没有误差容限（值必须完全相等）
eq2 = np.array_equal(a,b)
print('-'*30)
print(eq2)

[1 0 0 1 1]
------------------------------
[1 0 1 1 0]
------------------------------
False
------------------------------
False


In [46]:
# task43
# 把数组变为只读
a = np.zeros(5)
a.flags.writeable = False

In [47]:
# task44
# 将一个10x2的笛卡尔坐标矩阵转换为极坐标
a = np.random.random((10,2))
x,y = a[:,0],a[:,1]
r = np.sqrt(x ** 2 + y ** 2)
t = np.arctan2(y,x)
print(r)
print('-'*30)
print(t)

[0.7477733  0.72710292 1.00402108 0.84105698 1.23232313 1.02212603
 0.97306575 0.73050191 0.98040467 0.29341789]
------------------------------
[1.01646995 1.52985984 0.97480256 0.83081847 0.75123175 0.40459558
 1.33651039 1.1684748  0.14049209 1.18587292]


In [48]:
# task45
# 创建一个大小为10的随机向量并且将该向量中最大的值替换为0
a = np.random.random(10)
print(a)
print('-'*30)
a[a.argmax()] = 0
print(a)

[0.47723129 0.12867796 0.83720144 0.1654     0.63433502 0.16405114
 0.55208272 0.75007866 0.10685408 0.09092501]
------------------------------
[0.47723129 0.12867796 0.         0.1654     0.63433502 0.16405114
 0.55208272 0.75007866 0.10685408 0.09092501]


In [49]:
# task46
# 创建一个结构化数组，其中x和y坐标覆盖[0, 1]x[1, 0]区域
a = np.zeros((5,5),[('x',float),('y',float)])
a['x'],a['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [50]:
# task47
# 给定两个数组X和Y，构造柯西(Cauchy)矩阵C ()
X = np.arange(8)
print(X)
print('-'*30)
Y = X +0.5
print(Y)
print('-'*30)
c = 1/np.subtract.outer(X,Y)
print(c)
print('-'*30)
print(np.linalg.det(c))

[0 1 2 3 4 5 6 7]
------------------------------
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
------------------------------
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
------------------------------
3638.1636371179666


In [51]:
# task48
# 打印每个numpy 类型的最小和最大可表示值
for d in [np.int8,np.int32,np.int64]:
    print(np.iinfo(d).min)
    print(np.iinfo(d).max)
    print('-'*30)
for d in [np.float32,np.float64]:
    print(np.finfo(d).min)
    print(np.finfo(d).max)
    print(np.finfo(d).eps)
    print('-'*30)

-128
127
------------------------------
-2147483648
2147483647
------------------------------
-9223372036854775808
9223372036854775807
------------------------------
-3.4028235e+38
3.4028235e+38
1.1920929e-07
------------------------------
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16
------------------------------


In [52]:
# task49
# 如何打印数组中所有的值
# 打印出所有行、所有列
np.set_printoptions(threshold=None)
a = np.zeros((16,16))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [53]:
# task50
# 如何在数组中找到与给定标量接近的值
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

51
